apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8spipeline.fullname" . }}
  labels:
    {{- include "k8spipeline.labels" . | nindent 4 }}
data:
  application.yaml: |-
{{- if .Values.configmap }}
{{ tpl .Values.configmap . | indent 4 }}
{{- end }}
