apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "k8spipeline.fullname" . }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules: {{ toYaml .Values.ingress.rules | nindent 4 }}
