apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8spipeline.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8spipeline.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8spipeline.fullname" . }}