{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8spipeline.serviceAccountName" . }}
  labels:
{{- include "k8spipeline.labels" . | nindent 4 }}
{{- end -}}
