apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: k8spipeline
  name: k8spipeline
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8spipeline
  labels:
    app: k8spipeline
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io